# ==============================================================
# 선박 도장 품질 결함 탐지 - YOLO11m 베이스라인 학습 설정 파일
# ==============================================================

# 1. 모델 설정
model_path: "yolo11m.pt"    # 불러올 사전 학습 모델 가중치 (베이스라인용)

# 2. 하드웨어 및 리소스 설정
device: 0                   # 사용할 GPU 번호 (RTRX 3090)
batch: 32                   # 배치 사이즈 (RTX 3090 기준 32 권장 VARAM 16GB/32GB)
workers: 4                  # 데이터 로딩 멀티프로세싱 코어 수
cache: False                # RAM 데이터 캐싱 여부 (OOM 방지 위해 False 권장)

# 3. 데이터 및 학습 하이퍼파라미터
data: "../data/ship_paint_data.yaml"  # 데이터셋 경로 명세서
imgsz: 640                  # 입력 이미지 해상도 (640 고정으로 동등 비교)
epochs: 100                 # 최대 학습 에폭
#patience: 20                
#dropout: 0.15 

# 4. 부가 기능
val: True                   # 매 에폭마다 검증(Validation) 수행
plots: True                 # 학습 결과 그래프 및 시각화 저장