# ==============================================================
# 선박 도장 품질 결함 탐지 - Swin-YOLO26m 하이브리드 학습 설정 파일
# ==============================================================

# 1. 모델 설정 (핵심 변경점)
# .pt(가중치)가 아닌, 우리가 설계할 아키텍처를 바라보게 합니다.
model_path: "../models/swin_yolo26.py"    # TO-DO 검토 필요.

# 2. 하드웨어 및 리소스 설정 (RTX 3090 맞춤형)
device: 0                   # 사용할 GPU 번호
batch: 16                   # 🚨 [주의] Swin 블록의 메모리 점유율이 높아 32 -> 16으로 하향 타협
workers: 4                  # 데이터 로딩 멀티프로세싱 코어 수 (Ryzen 5600X 기준)
cache: False                # RAM 데이터 캐싱 여부 (32GB RAM 보호를 위해 False 유지)

# 3. 데이터 및 학습 하이퍼파라미터 (공정 비교를 위해 베이스라인과 동일하게 통제)
data: "../data/ship_paint_data.yaml"  # 데이터셋 명세서 경로
imgsz: 640                  # 입력 이미지 해상도 (640 고정)
epochs: 100                 # 최대 학습 에폭
#patience: 20                
#dropout: 0.15 

# 4. 부가 기능
val: True                   # 검증 수행
plots: True                 # 그래프 및 시각화 저장